### ISSUE TITLE
privateRoom 功能待開發事項統整

### ISSUE THREAD

**Issue by WilliamTsou818** [WilliamTsou818/twitter-api-2020#103]
一、格式驗證相關

1. 希望在 messageSchema 加上 isRead 屬性 (布林值) 

- 狀況說明：

因為在私人聊天室時，如果確認對方目前也在聊天室內，我會希望儲存訊息的同時一併將 isRead 設定為 true，但以目前的 message schema ，剛才在 postman 測試時會顯示 isRead is not allowed 的錯誤訊息。

二、messageService 相關

1. 新增方法取得當前使用者的未讀訊息，暫定 messageService.checkUnreadMessage(currentUserId)

- 狀況說明：

希望在使用者每次登入、傳私訊時，可以即時更新目前未讀的訊息數量，目前的想法是以 currentUserId 為參數，搭配 count 方法去取得 isRead = false 的資料筆數。

另外，公開聊天室與私人聊天室的未讀訊息必須分開，但公開聊天室訊息的 isRead 欄位意義不大 (因為太多人了)，所以我認為沒辦法用 count 去計算 roomId = 5 的未讀訊息，目前的想法是先只回傳未讀私訊的數量，公開聊天室的未讀通知先暫不回傳

2. 新增方法更新當前使用者的未讀訊息，暫定 messageService.updateUnreadStatus(RoomId, currentUserId)

- 狀況說明：

希望在使用者每次進入私訊頻道時，及時將目前的所有私訊更新成 isRead =true 的狀態，因為進入頻道後前端就會渲染所有歷史訊息，應該也包含未讀的訊息，可以利用此方法更新 isRead 狀態。

**Comment by Kcih4518** [comment]
> 一、格式驗證相關
> 
> 希望在 messageSchema 加上 isRead 屬性 (布林值)
> 狀況說明：
> 因為在私人聊天室時，如果確認對方目前也在聊天室內，我會希望儲存訊息的同時一併將 isRead 設定為 true，但以目前的 message schema ，剛才在 postman 測試時會顯示 isRead is not allowed 的錯誤訊息。
> 

我想確認一下，你有重新執行過`npx sequelize db:migrate`呢?
這是我目前執行完migrate和seed的結果，已經存在isRead了
![image](https://user-images.githubusercontent.com/24835719/134768552-52942b99-56c9-4660-afea-95881abdb241.png)

**Comment by Kcih4518** [comment]
相關PR: https://github.com/WilliamTsou818/twitter-api-2020/pull/104
