### ISSUE TITLE
待修正 messageService.getPrivateRooms 的回傳格式

### ISSUE THREAD

**Issue by WilliamTsou818** [WilliamTsou818/twitter-api-2020#115]
**目標：**

1. client 端需要回傳格式新增一個 content，內容為各房間最新的訊息以方便渲染私訊列表

![image](https://user-images.githubusercontent.com/78346513/134785836-82e8153f-a6b7-4b3a-87a1-8e1eab1bd799.png)

2. 回傳的私訊列表以各房間最新的訊息 createdAt 由新到舊排序 (目前回傳格式中的 createdAt 是 member 資料表的)
3. 回傳格式中的 updatedAt, createdAt 應更正為最新訊息的建立時間、更新時間，而非 member 資料表的

**修改困難點：**

1. member 與 message 資料表無關聯，若使用 include { model: message } ， Sequelize 會報錯
2. 目前 getPrivateRooms 的撈取相依性較高，同時處理 API 與 joinPrivateRoom socket 事件，可能會必須大幅翻修，導致改A 壞B

**目前的想法：**

1. 維持原本的 getPrivateRooms 不動，另外開一個 getLatestMessage 的 service，在 getPrivateRooms 的 API controller 中呼叫 getPrivateRooms 和 getLatestMessage 兩個 service，再將資料整合後回傳。可確保 socket 事件維持運作，因為 getPrivateRooms 的 service 並未變動。

2. 直接用原生 SQL 翻修整個 getPrivateRooms 的撈取邏輯，因為原生 SQL 可以透過 inner join 從 member > room > message 一層一層去取得資料，迴避 Sequelize 的限制。缺點是 SQL 語法很複雜不太好想，而且很可能會導致 socket 事件那邊壞掉，需要一併調整。

3. 向助教求救 Q___Q ，覺得是目前最困難的難題，因為之前沒遇過資料表無關聯的情況。

**Comment by Kcih4518** [comment]
相關PR: https://github.com/WilliamTsou818/twitter-api-2020/pull/116

因為時間考量，決定開發getLatestMessages ，來回傳當前使用者所有PrivateRoom 的最新一筆訊息，而不更動原本的getPrivateRooms，避免原先邏輯錯誤。
