### ISSUE TITLE
新增一筆推文時，沒有擋超過140字

### ISSUE THREAD

**Issue by YPINPIN** [WilliamTsou818/twitter-api-2020#40]
問題描述
新增一筆推文時，沒有擋超過140字，也會成功

期望的行為
應該像設定的一樣顯示失敗
![image](https://user-images.githubusercontent.com/79194627/133469621-4b63768c-f7c5-4add-b8db-2cf2c52f628e.png)

Screenshots
如果文字無法完全描述的話請提供截圖。

備註
是否有其它資訊或是解法都可以提供。

**Comment by WilliamTsou818** [comment]
目前已在重構時一併透過驗證格式的套件補上限制，在 POSTMAN 本地測試確認可以阻擋超過 140 字，並回傳相應錯誤訊息。
後續會再部署至 Heroku 上

**Comment by Kcih4518** [comment]
目前已經導入joi的進行req驗証，也已經refactor進入codebase了。

修正的PR : https://github.com/WilliamTsou818/twitter-api-2020/pull/39
