### ISSUE TITLE
[API 討論] User/取得一名 id 相符的使用者 是否合適增加資料

### ISSUE THREAD

**Issue by indexhui** [WilliamTsou818/twitter-api-2020#41]
問題描述
User/取得一名 id 相符的使用者
https://wahp-simeple-twitter-api.herokuapp.com/api/users/user_id
1.userPofile頁面中有顯示 **推文數 跟隨者數 跟隨中數** 想問  User/取得一名 id 相符的使用者 可不可以像取得全部使用者資料拿得到這三項。(    "TweetsCount": 10,
    "FollowersCount": 0,
    "FollowingsCount": 0)
2.可不可以也有他是否被當前使用者追蹤 ("isFollowed": false,)

期望項目
TweetsCount ,FollowersCount,FollowingsCount,isFollowed

screenshots
![Hugh_Twitter – Figma](https://user-images.githubusercontent.com/19654281/133471579-bb1a4958-aed2-4216-91cd-5865f674cc3e.png)
![Hugh_Twitter – Figma](https://user-images.githubusercontent.com/19654281/133471608-41546cd6-a8da-4b69-93dd-82518f428bc7.png)

**Comment by WilliamTsou818** [comment]
了解，後端會在重構時一併補上～！

**Comment by Kcih4518** [comment]
目前已根據需求進行修正。

PR:  https://github.com/WilliamTsou818/twitter-api-2020/pull/44
