### ISSUE TITLE
請求所有推文的資料時，裡面的isLike是1或0

### ISSUE THREAD

**Issue by YPINPIN** [WilliamTsou818/twitter-api-2020#42]
問題描述
請求所有推文的資料時，裡面的isLike是1或0，是之後會修改嗎?
api/tweets

期望的行為
記得有說過已經改成true 跟 false了

Screenshots
如果文字無法完全描述的話請提供截圖。
![image](https://user-images.githubusercontent.com/79194627/133497577-9e6de062-8186-4637-a513-e1f5a7ddeab8.png)

備註
是否有其它資訊或是解法都可以提供。

**Comment by Kcih4518** [comment]
因為這邊的isLike是透過Database 去運算取得，
他會用1 / 0 來表示是否有存在，
不確能否更改為ture/false，
這邊會造成你們判斷上的問題嗎?

**Comment by WilliamTsou818** [comment]
雖然沒辦法在撈資料的當下就改為 true / false
但可以用 forEach 搭配 isLike = isLike ? true : false 或 Boolean(Number(isLike))，就能轉為 true / false 了
其他像是 isFollowed 的屬性也可以照這個方式轉換成 Boolean

我個人覺得可以在 server 端處理

https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Boolean

**Comment by YPINPIN** [comment]
這邊如果說你們方便改的話，可以麻煩你們幫我們統一改成ture/false嗎?
我們前端會比較好進行判斷，比較直覺

**Comment by Kcih4518** [comment]
這邊已經統一進行修正，回傳true/false

修改的PR: https://github.com/WilliamTsou818/twitter-api-2020/pull/44/files
