### ISSUE TITLE
取得符合 tweet_id 的推文與該推文的留言時，如果推文不存在資料庫，回傳的status是success

### ISSUE THREAD

**Issue by YPINPIN** [WilliamTsou818/twitter-api-2020#45]
問題描述
取得符合 tweet_id 的推文與該推文的留言時，如果推文不存在資料庫，回傳的status是success
api/tweets/tweet_id

期望的行為
希望可以收到的status是error，讓前端知道其實是沒有獲取資料的

Screenshots
![image](https://user-images.githubusercontent.com/79194627/133572491-0095392b-db6e-4f70-879d-b2baf7198e7b.png)

備註
是否有其它資訊或是解法都可以提供。

**Comment by Kcih4518** [comment]
目前在處理error handle 一起修正了。

PR: https://github.com/WilliamTsou818/twitter-api-2020/pull/49
