### ISSUE TITLE
POST /api/users : Account 驗證異常

### ISSUE THREAD

**Issue by Kcih4518** [WilliamTsou818/twitter-api-2020#47]
問題描述
註冊使用者時，Acoount 驗證沒有正常運作，我輸入為string 但他還是會顯示非string，而且

期望的行為
能正常驗証account 格式

Screenshots
如果文字無法完全描述的話請提供截圖。
![image](https://user-images.githubusercontent.com/24835719/133609044-b2294f33-1b61-470e-9216-0624b878d969.png)

備註
是否有其它資訊或是解法都可以提供。

**Comment by Kcih4518** [comment]
我好像也撞到postman的bug了.... 開一個新的tag就正常運作了，所以close。

**Comment by WilliamTsou818** [comment]
我這邊在 POSTMAN 測試輸入 string 是會通過驗證的



你能幫我跑看看自動測試嗎？

**Comment by WilliamTsou818** [comment]
阿好  了解 XDD
