### ISSUE TITLE
回覆推文相關後端驗證以及列表排序問題

### ISSUE THREAD

**Issue by YPINPIN** [WilliamTsou818/twitter-api-2020#48]
問題描述
回覆推文的上限測試後端沒有擋到140字。(tweets/tweet_id/replies)
另外推文的回覆列表排序希望可以最新的在上面，感覺比較正常。(api/tweets/tweet_id)

期望的行為
你期望收到什麼data或是功能。

Screenshots
![image](https://user-images.githubusercontent.com/79194627/133666899-731746a9-b162-489d-977a-49ee53f21d38.png)
備註
是否有其它資訊或是解法都可以提供。

**Comment by WilliamTsou818** [comment]
1. 目前格式驗證已經有擋下超過 140 字的留言  (P.S. 附圖的錯誤訊息格式請忽略，正式部署時回傳給前端的會是一個字串而非陣列)
![留言限制140字測試](https://user-images.githubusercontent.com/78346513/133716115-225c97d1-84f9-4b80-aa08-e19c48bfacef.png)

2. 特定推文的所有留言，目前撈取的排序邏輯確實是由舊到新 ( ASC )，會在下一次部署前改為由新到舊 ( DESC )

**Comment by Kcih4518** [comment]
目前排序會驗證都完成修正。

PR:  https://github.com/WilliamTsou818/twitter-api-2020/pull/50

**Comment by WilliamTsou818** [comment]
前端串接測試，推文回覆依然是由舊到新，待除錯

**Comment by Kcih4518** [comment]
修正 GET /api/tweets/:tweetId

PR:  https://github.com/WilliamTsou818/twitter-api-2020/pull/53

備註:
此次修正發現如果沒有加上order，可能每次看見的順序是不同的，mysql會自動選擇最佳路徑。

Ref:  https://stackoverflow.com/questions/8746519/sql-what-is-the-default-order-by-of-queries
