### ISSUE TITLE
編輯使用者未檢查 Email, Account, Name 是否重覆

### ISSUE THREAD

**Issue by WilliamTsou818** [WilliamTsou818/twitter-api-2020#55]
問題描述
編輯使用者的帳戶設定，可以修改為已經有人使用的 Email 或 Account

期望的行為
應該和註冊時一樣要擋下並顯示錯誤訊息，另外註冊使用者與編輯使用者時，Name 也要檢查是否重覆

Screenshots
如果文字無法完全描述的話請提供截圖。

備註
是否有其它資訊或是解法都可以提供。

**Comment by indexhui** [comment]
`經過測試呀，確實可以擋住用戶重複其他用戶的 Email, Account, Name 感謝!
`

問題描述:
想討論可不可以如果是自己的本人的  Email, Account, Name 重複自己的狀況下不要擋下?
![Frame 132](https://user-images.githubusercontent.com/19654281/133824741-6cf52209-52ec-49ca-baa6-e7f5902bbbd8.png)

**Comment by WilliamTsou818** [comment]
目前已修改完成，POSTMAN 測試過後也沒問題，下一版 deploy 時會修正  

- 本圖的當前使用者為 User1，修改資料重覆的是本人資料，因此即使重覆也會通過修改並回傳成功訊息
![putUser不擋本人重覆的資料(postman(User1本人))](https://user-images.githubusercontent.com/78346513/133835959-e1bf2c80-6c1f-460b-8ab7-08add7390bec.png)


- 本圖的當前使用者為 User1，修改 Email 為 User4 已經重覆使用的 Email 資料，正常顯示 Email 已存在的錯誤訊息
![putUser不擋本人重覆的資料(postman(User1修改))](https://user-images.githubusercontent.com/78346513/133836345-d58474dc-b0fc-45af-92b9-9c07a412eb5d.png)

**Comment by Kcih4518** [comment]
已進行修正，為原本user的email、account、email，則不會出現錯誤。

PR: https://github.com/WilliamTsou818/twitter-api-2020/pull/60
