### ISSUE TITLE
取得 id 相符的使用者推文清單 缺少updatedAt的資料

### ISSUE THREAD

**Issue by YPINPIN** [WilliamTsou818/twitter-api-2020#58]
問題描述
取得 id 相符的使用者推文清單 缺少updatedAt的資料，所有推文的部分就有
api/users/user_id/tweets

期望的行為
希望補上updatedAt的資料

Screenshots
![image](https://user-images.githubusercontent.com/79194627/133807625-f2e1d047-e924-4fc2-9463-0c837376b027.png)

備註
是否有其它資訊或是解法都可以提供。

**Comment by WilliamTsou818** [comment]
OK，明天我會再補上
其他 user 相關的數據路由，如果有缺少 updatedAt ，我也會先放上去
前端這邊就在依自己的需求去使用

**Comment by YPINPIN** [comment]
好的~感謝!!

**Comment by Kcih4518** [comment]
已進行修正，會在/api/users 相關API中回傳updatedAt。

PR: https://github.com/WilliamTsou818/twitter-api-2020/pull/60
