### ISSUE TITLE
當合法的User 沒有跟隨者或跟隨中，取得 User 這兩項資料會報401

### ISSUE THREAD

**Issue by indexhui** [WilliamTsou818/twitter-api-2020#59]
問題描述
當User 沒有跟隨者或跟隨中，取得User 這兩項資料會報401。

期望的行為

 我期待我打這兩隻api ,https://wahp-simeple-twitter-api.herokuapp.com/ api/users/user_id/followings & https://wahp-simeple-twitter-api.herokuapp.com/api/users/user_id/followers
User/取得 id 相符的使用者被誰追蹤的清單
User/取得 id 相符的使用者正在追蹤的清單
當使用者存在時，資料為空得時候正常傳陣列 ，回傳success然後是空陣列

也就是期待是上個版本的。
使用者ID是不存在的再報錯

Screenshots
![Screenshot - 2021-09-18 01 06 14](https://user-images.githubusercontent.com/19654281/133829255-a8db8c12-ab49-4362-a52d-3b6302bdcce5.png)

![Screenshot - 2021-09-18 01 00 17](https://user-images.githubusercontent.com/19654281/133829266-ba257fd6-00fc-45d0-9e91-a8c46c1deb26.png)

備註
是否有其它資訊或是解法都可以提供。

**Comment by WilliamTsou818** [comment]
沒問題，明天我會再改回上一版的方式回傳空陣列與 success 訊息

補充提問：

- 取得使用者推文 /api/users/:user_id/tweets (對應推文頁面)
- 取得使用者有留言的推文 /api/users/:user_id/replied_tweets (對應推文與回覆頁面)
- 取得使用者喜歡的內容 /api/users/:user_id/likes (對應喜歡的內容頁面)

這三支 api 在現版本的 heroku api 站也會在查無資料時報錯，需要一併改成回傳空陣列的版本嗎？

**Comment by YPINPIN** [comment]
對的 這三支api也是 麻煩了

**Comment by Kcih4518** [comment]
已進行修正，會回純回傳success的空陣列。

PR: https://github.com/WilliamTsou818/twitter-api-2020/pull/60
