### ISSUE TITLE
GET: /api/admin/users 回傳的user 沒有固定排序

### ISSUE THREAD

**Issue by Kcih4518** [WilliamTsou818/twitter-api-2020#68]
問題描述
在後台查看使用者列表時，重新整理後會看見不同順序的使用者名單。

期望的行為
每次的使用者名單，是固定順序。

Screenshots
![Sep-18-2021 20-00-40](https://user-images.githubusercontent.com/24835719/133888091-cbb19832-1735-45fa-8904-ac9aadd6ade9.gif)

備註
是否有其它資訊或是解法都可以提供。

**Comment by WilliamTsou818** [comment]
目前後台撈取使用者列表的邏輯是按照：

1. 推文數由多到少 (User Story 規範)
2. 建立時間由新到舊 (自行添加，目的是在推文數相同時，有第二個排序依據)

問題發生原因：

從 GIF 當中會不斷更動順序的只有種子資料的使用者，推測是因為推文數與建立時間的資料完全相同，因此資料庫會隨機回傳
但後來建立的使用者，或是有增刪推文的種子資料，依然會按照順序排列

**Comment by WilliamTsou818** [comment]
可以考慮修改第二個排序的邏輯，或是再增加第三個排序的欄位

**Comment by Kcih4518** [comment]
好的，那先按照目前設計就好。
