### ISSUE TITLE
error message 的資料希望改用其他符號連接

### ISSUE THREAD

**Issue by YPINPIN** [WilliamTsou818/twitter-api-2020#73]
問題描述
error message 的資料，目前是用逗號連接，但是會遇到像截圖中的帳號限制提示內容本身就有逗號，
這樣在判斷message的時候也會被判斷成兩個error。

期望的行為
希望連接的符號可以換成其他的符號，例如 |

Screenshots
![image](https://user-images.githubusercontent.com/79194627/134167517-ae80cfdd-d99d-4ba1-a896-cca3439df05a.png)

備註
是否有其它資訊或是解法都可以提供。

**Comment by Kcih4518** [comment]
已進行修正，error message 的資料改用' | ' 進行串接。

PR:  https://github.com/WilliamTsou818/twitter-api-2020/pull/75
