### ISSUE TITLE
取得公開聊天室的歷史訊息 api，資料沒有user

### ISSUE THREAD

**Issue by WilliamTsou818** [WilliamTsou818/twitter-api-2020#99]
問題描述
回傳的訊息陣列中，User與 UserId 的欄位沒有值。

期望的行為
應該會有對應的值，可以讓前端渲染。

Screenshots
![image](https://user-images.githubusercontent.com/78346513/134737204-58ffccee-a9dd-4843-8931-ca9e273fdcdf.png)

Heroku 遠端資料庫截圖

![heroku訊息資料](https://user-images.githubusercontent.com/78346513/134737530-794939ab-b612-4d05-8e07-229364bdbb53.png)

備註

**Comment by Kcih4518** [comment]
這個問題主要為:

1. 在送出訊息時，message需要夾帶    ` const { UserId, RoomId, content } = message`  ，除了Public RoomId 固定提供外，UserId是需要包進message，這邊會是null 的時候代表在發送message時，可能參數設定錯誤。

2.  因為沒有UserId 會導致，在取得User 資訊時沒有辦法從User model進行關連，所以會是null。
 
3. GET /api/messages/:RoomId的 邏輯上應該是沒有錯誤的，主要就是要確認源頭，那些message是如何產生的，另外我也加上驗証避免UserId、RoomId、content在null時，還會存入database。
